SELECT NAME, DATETIME
FROM (
    SELECT ROWNUM, AI.NAME, AI.DATETIME
    FROM ANIMAL_INS AI LEFT OUTER JOIN ANIMAL_OUTS AO ON(AI.ANIMAL_ID = AO.ANIMAL_ID)
    WHERE AO.DATETIME IS NULL
    ORDER BY AI.DATETIME
)
WHERE ROWNUM >=1 AND ROWNUM <4