-- 그룹별 조건에 맞는 식당 목록 출력하기
SELECT MEMBER_NAME,	REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
from MEMBER_PROFILE B, REST_REVIEW c,
 (select MEMBER_ID, count(*) cnt
      from REST_REVIEW
      group by MEMBER_ID
     order by cnt DESC FETCH NEXT ROW WITH TIES)A
     where B.MEMBER_ID = A.MEMBER_ID
     and B.MEMBER_ID = C.MEMBER_ID
order by REVIEW_DATE asc, REVIEW_TEXT asc

-- SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
--   FROM MEMBER_PROFILE A
--   JOIN
-- (SELECT MEMBER_ID, COUNT(*) CNT
--    FROM REST_REVIEW
--   GROUP BY MEMBER_ID
--   ORDER BY CNT DESC FETCH NEXT ROW WITH TIES) B
--     ON A.MEMBER_ID = B.MEMBER_ID
--   JOIN REST_REVIEW C
--     ON A.MEMBER_ID = C.MEMBER_ID
--  ORDER BY REVIEW_DATE, REVIEW_TEXT;